# Generated by Django 6.1.1 on 2026-09-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
